# Generated by Django 4.1.1 on 2022-09-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TweetApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet',
            new_name='text',
        ),
        migrations.AddField(
            model_name='tweet',
            name='parent_tweet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TweetApp.tweet'),
        ),
    ]
