# Generated by Django 4.1.1 on 2022-09-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TweetApp', '0002_rename_tweet_tweet_text_tweet_parent_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmedia',
            name='tweet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tweet_media', to='TweetApp.tweet'),
        ),
    ]
