# Generated by Django 4.1.1 on 2022-09-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_otp_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
