# Generated by Django 4.1.1 on 2022-09-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='username',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
