# Generated by Django 4.1.1 on 2022-09-20 12:46

import UserApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_otp_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default=None, null=True, upload_to=UserApp.models.upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='special_status',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(default=None, null=True),
        ),
    ]
